server:
  port: 8080

spring:
  application:
    name: federation-api
  datasource:
    url: jdbc:postgresql://localhost:5432/federation_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
        mode: never
    jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true